import Foundation
import QuilNodeCore
import XCTest

final class CargoLockfileIntegrityTests: XCTestCase {
    private let upstream = """
        # This file is automatically @generated by Cargo.
        version = 4

        [[package]]
        name = "quil-execution"
        version = "0.1.0"
        dependencies = [
         "rocksdb",
         "serde",
        ]

        [[package]]
        name = "rocksdb"
        version = "0.24.0"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "fixture-rocksdb-checksum"

        [[package]]
        name = "serde"
        version = "1.0.0"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "fixture-serde-checksum"
        dependencies = [
         "rocksdb",
        ]

        """

    func testStaleLocalDependencyEdgeCanBeRemovedWithEveryExternalRecordIntact() {
        let repaired = upstream.replacingOccurrences(
            of: " \"rocksdb\",\n", with: "", range: upstream.range(of: " \"rocksdb\",\n"))
        XCTAssertTrue(permitted(repaired))
        XCTAssertTrue(permitted(upstream))
    }

    func testExternalVersionsChecksumsSourcesAndDependencyGraphCannotChange() {
        for change in [
            upstream.replacingOccurrences(of: "version = \"0.24.0\"", with: "version = \"0.25.0\""),
            upstream.replacingOccurrences(of: "fixture-serde-checksum", with: "changed-checksum"),
            upstream.replacingOccurrences(
                of: "registry+https://github.com/rust-lang/crates.io-index", with: "git+https://example.invalid/repo"),
            upstream.replacingOccurrences(of: " \"rocksdb\",\n", with: ""),
        ] {
            XCTAssertFalse(permitted(change))
        }
    }

    func testLocalPackageIdentityMetadataAndLockFormatCannotChange() {
        for change in [
            upstream.replacingOccurrences(of: "name = \"quil-execution\"", with: "name = \"substitute\""),
            upstream.replacingOccurrences(of: "version = \"0.1.0\"", with: "version = \"0.2.0\""),
            upstream.replacingOccurrences(of: "version = 4", with: "version = 3"),
            upstream + "\n[[package]]\nname = \"injected\"\nversion = \"1.0.0\"\n",
            upstream.replacingOccurrences(of: " \"serde\",", with: " arbitrary = true"),
        ] {
            XCTAssertFalse(permitted(change))
        }
        XCTAssertFalse(CargoLockfileIntegrity.permitsLocalDependencyRepair(upstream: Data(), resolved: Data()))
    }

    private func permitted(_ candidate: String) -> Bool {
        CargoLockfileIntegrity.permitsLocalDependencyRepair(
            upstream: Data(upstream.utf8), resolved: Data(candidate.utf8))
    }
}
